version: "3.2"
services:

  redis:
    image: 'redis:latest'
    container_name: "redis-server"
    command: --appendonly yes
    ports:
      - "6379:6379"
    expose:
      - 6379
    volumes:
      - ./redis-data:/data:rw
    networks:
      ip_info:
        ipv4_address: 172.16.0.5

  ip-info:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "ip-info"
    ports:
      - "8080:8080"
    networks:
      ip_info:
        ipv4_address: 172.16.0.6

networks:
  ip_info:
    ipam:
      driver: default
      config:
        - subnet: "172.16.0.0/24"